# Generated by Django 4.2.2 on 2023-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Fitness', 'Fitness'), ('Other', 'Other'), ('Work', 'Work'), ('Education', 'Education'), ('Travel', 'Travel'), ('Social', 'Social'), ('Health', 'Health'), ('Hobbies', 'Hobbies'), ('Finance', 'Finance')], max_length=100, null=True),
        ),
    ]
