# Generated by Django 4.2.2 on 2023-06-27 21:08

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('tasksApp', 'Category')

    # Define the predefined choices
    predefined_choices = [
        ('Personal', 'Personal'),
        ('Work', 'Work'),
        ('Health', 'Health'),
        ('Fitness', 'Fitness'),
        ('Education', 'Education'),
        ('Finance', 'Finance'),
        ('Social', 'Social'),
        ('Travel', 'Travel'),
        ('Hobbies', 'Hobbies'),
        ('Other', 'Other'),
    ]

    for choice in predefined_choices:
        Category.objects.create(name=choice[0])


class Migration(migrations.Migration):
    dependencies = [
        ('tasksApp', '0010_remove_category_color'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
