# Generated by Django 4.2.2 on 2023-06-27 21:27

from django.db import migrations

from taskify.tasksApp.models import TaskStatus


def populate_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('tasksApp', 'TaskStatus')

    predefined_choices = [
        ('Not Started', 'Not Started'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
    ]

    # Create TaskStatus instances for each choice
    for choice in predefined_choices:
        TaskStatus.objects.create(status=choice[0])


class Migration(migrations.Migration):
    dependencies = [
        ('tasksApp', '0012_remove_task_user'),
    ]

    operations = [
        migrations.RunPython(populate_task_statuses),
    ]
