# Generated by Django 4.2.2 on 2023-06-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0016_alter_category_name_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(limit_choices_to={'name__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='tasksApp.category'),
        ),
    ]
