# Generated by Django 4.2.2 on 2023-07-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0026_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=2, limit_choices_to={'status__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasksApp.taskstatus'),
        ),
    ]
