# Generated by Django 4.2.3 on 2023-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0027_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
