# Generated by Django 4.2.2 on 2023-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Education', 'Education'), ('Finance', 'Finance'), ('Social', 'Social'), ('Travel', 'Travel'), ('Hobbies', 'Hobbies'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
