# Generated by Django 4.2.2 on 2023-06-27 20:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
