# Generated by Django 4.2.2 on 2023-06-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0009_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
