# Generated by Django 4.2.2 on 2023-06-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0017_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Not Started', limit_choices_to={'status__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='tasksApp.taskstatus'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(default='Not Started', max_length=100),
        ),
    ]
