# Generated by Django 4.2.2 on 2023-07-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0021_task_reminder_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasksApp.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='enable_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
