# Generated by Django 4.2.2 on 2023-07-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0025_task_start_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default='Not Started', limit_choices_to={'status__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasksApp.taskstatus'),
        ),
    ]
