# Generated by Django 4.2.3 on 2023-07-26 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0028_task_origin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=models.DateField(default=datetime.date(2023, 7, 26)), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
    ]
