# Generated by Django 4.2.3 on 2023-08-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remindersApp', '0004_alter_reminder_reminder_datetime'),
        ('tasksApp', '0038_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remindersApp.reminder'),
        ),
    ]
