# Generated by Django 4.2.4 on 2023-08-11 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0040_remove_task_enable_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=1, limit_choices_to={'name__isnull': False}, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasksApp.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Priority must be between 1 and 5')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'status__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasksApp.taskstatus'),
        ),
    ]
