# Generated by Django 4.2.3 on 2023-07-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='due_date',
            new_name='reminder_datetime',
        ),
    ]
