# Generated by Django 4.2.3 on 2023-07-31 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remindersApp', '0003_remove_reminder_is_completed_remove_reminder_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
