# Generated by Django 4.2.4 on 2023-08-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindersApp', '0005_reminder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
    ]
